### ISSUE TITLE
UML .png files not created after running extension 

### ISSUE THREAD

**Issue by BrianJVarley** [immament/vscode-ngrx-uml#13]
hi @immament , I'm hoping to use this extension to build some UML diagrams for my app. But after the extension finished running, I don't see any generated `.png` diagrams:

The `wsd` and `json` folders are present, but not `png/`.

Is there any extra config required to enable PNG generation?

**Comment by BrianJVarley** [comment]
I had to enable the generate image setting in extension settings:

![image](https://user-images.githubusercontent.com/6731968/106136686-88379c80-6161-11eb-874a-4618bcc1fa58.png)

**Comment by immament** [comment]
Great :)

**Comment by immament** [comment]
Available options can be find in README:

https://github.com/immament/vscode-ngrx-uml/blob/master/README.md#extension-settings
